# Sheet Information
[main]
image='smb3map/font.png'
rows=10
cols=10
ascent=16
descent=-2

# Default Glyph Properties
[glyphdefaults]
baseline=1
width=16

# Glyph Map (optional concise way to indicate the row/column of characters for simple cases)
[glyphmap]
row1='0123456789'
row2='ABCDEFGHIJ'
row3='KLMNOPQRST'
row4='UVWXYZ-_=+'
row5='abcdefghij'
row6='klmnopqrst'
row7='uvwxyz,.{}'
row8='`~!@#$%^&*'
row9='()<>[]/?\|'
row10=':;'" '

[i]
width=8

[']
width=8